### ISSUE TITLE
Search by end date not working

### ISSUE THREAD

**Issue by hking21** [mMckibbin1/Hotel-Booking-System-training#3] opened 2019-09-27 09:30 UTC
When an end date is entered into the entry box, and a check box is selected, it should mean that all bookings before this date appear. When testing the code, no bookings appeared in the treeview.

**Comment by mMckibbin1** [comment] 2019-09-30 08:58
This was caused by a syntax error in a SQL statement. this caused no data to be returned this as been fixed now functions correctly

**Closed as completed by mMckibbin1** 2019-09-30 08:58 UTC
Labels: bug
